#include <NeuroGreen_inferencing.h>  // Generated by Edge Impulse

void runAI() {
  float input[] = {temp, humidity, soilMoisture, lux, edaValue};
  ei_impulse_result_t result;
  run_classifier(input, &result);
  Serial.print("Predicted emotion: ");
  Serial.println(result.classification[0].label);
}